In [1]:
from __future__ import print_function
import os
import numpy as np
from numpy import newaxis
from sklearn import preprocessing
np.random.seed(1337)

import keras
from keras.utils.np_utils import to_categorical
from keras.layers import Dense, Input, Flatten
from keras.layers import Dropout
from keras.models import Model,Sequential
import sys

import pandas as pd
import random

Using TensorFlow backend.


# Reading in data

In [100]:
print("Data read started...")
data = pd.read_csv("result_tetris.csv")
data = data.as_matrix()
print ("Data read finished.")

print(data.shape)

Data read started...
Data read finished.
(603, 11)


# Eliminate EEG data

In [101]:
for i in range (1,5):
    data = np.delete(data, i, 1) 

data.shape

(603, 7)

In [102]:
data[1]

array(['tetris1', 84441.0, 56966.0, 1688.7, 4.378305084745762, 335.19,
       537.78], dtype=object)

# Dictionary for the levels

In [103]:
#level=["nback gyakorlas","0back","1back","2back","3back"]
level=["tetris1","tetris2","tetris3"]
level2int = dict((p, i) for i, p in enumerate(level))
int2level = dict((i, p) for i, p in enumerate(level))

# Z normalize

In [104]:
for i in range (1,7):
    data[:, i] = preprocessing.scale(data[:, i])

/home/amoro/anaconda2/lib/python2.7/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype object was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)
/home/amoro/anaconda2/lib/python2.7/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype object was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)
/home/amoro/anaconda2/lib/python2.7/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype object was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)
/home/amoro/anaconda2/lib/python2.7/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype object was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)
/home/amoro/anaconda2/lib/python2.7/site-packages/sklearn/utils/validation.py:420: DataConve

In [105]:
for i in range(len(data)):
    data[i, 0] = level2int[data[i, 0]]

x_data = data[:, 1:]
y_data = data[:, 0]

# One-hot encoding

In [106]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder()
y_one_hot = ohe.fit_transform(y_data.reshape(-1,1)).toarray()
print(y_one_hot)

[[ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 ..., 
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]]


# Shuffle data

In [107]:
indices = np.arange(x_data.shape[0])
np.random.shuffle(indices)

x_data = x_data[indices]
y_one_hot = y_one_hot[indices]

# Divide into train, validation and test data

In [108]:
len_data = len(x_data)

nb_test = int(len_data*0.15)
nb_validation = int(len_data*0.15)
nb_train = int(len_data*0.7)

end_valid = nb_train+nb_validation

x_train = x_data[0:nb_train]
y_train = y_one_hot[0:nb_train]

x_valid = x_data[nb_train:end_valid]
y_valid = y_one_hot[nb_train:end_valid]

x_test = x_data[end_valid:]
y_test = y_one_hot[end_valid:]

In [109]:
print(x_train.shape, y_train.shape, x_valid.shape, y_valid.shape, x_test.shape, y_test.shape)

(422, 6) (422, 3) (90, 6) (90, 3) (91, 6) (91, 3)


# Build the net

In [110]:
model = Sequential()

model.add(Dense(200, input_shape=(6,)))
model.add(Dropout(0.25))
model.add(Dense(200, activation='relu'))
model.add(Dropout(0.25))
model.add(Dense(200, activation='relu'))
model.add(Dropout(0.25))
model.add(Dense(3, activation='softmax'))

In [111]:
batch_size = 50
epochs = 150
earlyStopping=keras.callbacks.EarlyStopping(monitor='val_loss', patience=15, verbose=0, mode='auto')

model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['acc'])
model.fit(x_train, y_train, nb_epoch=epochs,batch_size=batch_size, 
          callbacks=[earlyStopping], shuffle=True, validation_data = (x_valid, y_valid))

Train on 422 samples, validate on 90 samples
Epoch 1/150
422/422 [==============================] - 0s - loss: 0.8666 - acc: 0.5640 - val_loss: 0.5663 - val_acc: 0.7444
Epoch 2/150
422/422 [==============================] - 0s - loss: 0.6128 - acc: 0.6303 - val_loss: 0.4786 - val_acc: 0.7444
Epoch 3/150
422/422 [==============================] - 0s - loss: 0.5609 - acc: 0.6706 - val_loss: 0.4488 - val_acc: 0.7444
Epoch 4/150
422/422 [==============================] - 0s - loss: 0.5248 - acc: 0.7109 - val_loss: 0.4154 - val_acc: 0.7444
Epoch 5/150
422/422 [==============================] - 0s - loss: 0.5142 - acc: 0.6919 - val_loss: 0.4103 - val_acc: 0.7667
Epoch 6/150
422/422 [==============================] - 0s - loss: 0.4833 - acc: 0.7180 - val_loss: 0.3838 - val_acc: 0.7778
Epoch 7/150
422/422 [==============================] - 0s - loss: 0.4768 - acc: 0.7464 - val_loss: 0.3841 - val_acc: 0.7667
Epoch 8/150
422/422 [==============================] - 0s - loss: 0.4797 - acc: 0.7346 

In [112]:
model.evaluate(x_test, y_test, batch_size=batch_size)

50/91 [===============>..............] - ETA: 0s

[0.43475596655856125, 0.69230771457755957]

In [113]:
from sklearn.metrics import classification_report,confusion_matrix

y_pred = model.predict_classes(x_test)
print(y_pred)

p=model.predict_proba(x_test)

#target_names = ['class 0(nback gyakorlas)', 'class 1(0back)', 'class 2(1back)', 'class 3(2back)', 'class 4(3back)']
target_names = ['class 0(tetris1)', 'class 1(tetris2)', 'class 2(tetris3)']
print(classification_report(np.argmax(y_test,axis=1), y_pred,target_names=target_names))
print(confusion_matrix(np.argmax(y_test,axis=1), y_pred))

32/91 [=========>....................] - ETA: 0s[0 0 1 2 2 2 0 2 2 2 2 1 2 0 1 1 0 0 0 1 0 2 2 0 1 0 2 2 1 0 2 2 1 2 2 2 1
 0 0 0 0 0 1 0 0 0 2 1 1 1 2 0 1 1 0 1 0 2 2 2 0 2 0 2 2 0 0 0 1 0 2 2 2 0
 2 1 2 0 2 1 0 1 2 0 1 2 2 2 2 0 1]
32/91 [=========>....................] - ETA: 0s                  precision    recall  f1-score   support

class 0(tetris1)       1.00      1.00      1.00        33
class 1(tetris2)       0.59      0.41      0.48        32
class 2(tetris3)       0.47      0.65      0.55        26

     avg / total       0.71      0.69      0.69        91

[[33  0  0]
 [ 0 13 19]
 [ 0  9 17]]
